- name: activating RH 6.5 intertal repo
  copy: src=RH_6.5_internal.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: activating EPEL internal repo
  copy: src=EPEL_internal.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: install the latest version of nginx
  yum: name=nginx state=latest

- name: set nginx as a service
  service: name=nginx enabled=yes

- name: delete default vhost
  action: file path=/etc/nginx/conf.d/default.conf state=absent

- name: create nginx.conf
  action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: uploading SSL certificate files
  copy: src="{{active_env_home}}/files/nginx/ccb.{{item}}"
        dest=/etc/nginx/ssl/
        owner=root group=root mode=0600
  with_items:
    - key
    - crt

- name: add nginx group {{ installing_group }} vhost
  action: template src=building-blocks.vhost.j2 dest=/etc/nginx/conf.d/{{ installing_group }}.conf

- name: start nginx service
  service: name=nginx state=restarted